#%RAML 1.0 DataType
type: object
properties:
  id:
    type: integer
    description:  auto generated
  street:
    required: true
    type: string
  city:
    required: true
    type: string
  postcode:
    required: true
    type: integer
  phone:
    type: integer
  email:
    type: string
